# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish to Maven Central

run-name: Publish to Maven Central and switch over to ${{ inputs.developmentVersion }}

on:
  workflow_dispatch:
    inputs:
      developmentVersion:
        description: "Next development version"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Print the next development version
        run: echo "${DEVELOPMENT_VERSION}"
        env:
          DEVELOPMENT_VERSION: ${{ inputs.developmentVersion }}

      - name: Configure Git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Build and deploy with Maven
        run: mvn -B -Pcicd release:clean release:prepare release:perform -DdevelopmentVersion=${DEVELOPMENT_VERSION}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          DEVELOPMENT_VERSION: ${{ inputs.developmentVersion }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}